(source melpa)
(source gnu)
(source org)

(package "misenplace" "0.0.1" "My Mis En Place")

(package-file "misenplace.el")
(files ("*.el" "assets"))

(development
 (depends-on "undo-tree" :git "http://www.dr-qubit.org/git/undo-tree.git")
 (depends-on "xelb" :git "https://github.com/ch11ng/xelb.git")
 (depends-on "alert" :git "https://github.com/jwiegley/alert.git")
 (depends-on "alarm-clock")
 (depends-on "auctex")
 (depends-on "auctex-latexmk")
 (depends-on "auto-complete")
 (depends-on "ac-rtags")
 (depends-on "awesome-tab" :git "https://github.com/manateelazycat/awesome-tab")
 (depends-on "all-the-icons")
 (depends-on "ace-jump-mode")
 (depends-on "bind-key")
 (depends-on "cask")
 (depends-on "command-log-mode")
 (depends-on "cheatsheet")
 (depends-on "counsel")
 (depends-on "counsel-gtags")
 (depends-on "counsel-org-clock")
 (depends-on "cmake-ide")
 (depends-on "dash")
 (depends-on "dashboard" :git "https://github.com/jordans1882/emacs-dashboard.git" :files ("*.el" "banners"))
 (depends-on "dimmer")
 (depends-on "doom-modeline")
 (depends-on "dumb-jump")
 (depends-on "drag-stuff")
 (depends-on "egg-timer")
 (depends-on "ecukes")
 (depends-on "ein")
 (depends-on "elscreen")
 (depends-on "ert-async")
 (depends-on "ert-runner")
 (depends-on "evil")
 (depends-on "evil-nerd-commenter")
 (depends-on "eyebrowse")
 (depends-on "ess")
 (depends-on "esup")
 (depends-on "exec-path-from-shell")
 (depends-on "expand-region")
 (depends-on "exwm" :git "https://github.com/ch11ng/exwm.git")
 (depends-on "exwm-x" :git "https://github.com/tumashu/exwm-x.git")
 (depends-on "f")
 (depends-on "flycheck")
;; (depends-on "frame-cmds")
 (depends-on "flycheck-cask")
 (depends-on "fringe-helper")
 (depends-on "git-auto-commit-mode")
 (depends-on "git-gutter")
 (depends-on "git-gutter-fringe")
 (depends-on "goto-chg")
 (depends-on "ghc")
 (depends-on "haskell-mode")
 (depends-on "htmlize")
 (depends-on "idle-highlight-mode")
 (depends-on "ivy")
 (depends-on "ivy-rtags")
;; (depends-on "ivy-bibtex")
 (depends-on "ivy-posframe")
 (depends-on "ivy-prescient")
 (depends-on "lorem-ipsum")
 (depends-on "magit")
 (depends-on "misenplace-snippets" :git "https://gitlab.com/jordans1882/misenplace-snippets.git" :files ("*.el" "snippets"))
 (depends-on "mpc")
 (depends-on "multiple-cursors")
 (depends-on "nyan-mode")
 (depends-on "org")
 (depends-on "org-bullets")
 (depends-on "org-projectile")
 (depends-on "org-ref")
 (depends-on "ox-reveal")
 (depends-on "org-pomodoro")
 (depends-on "pallet")
 (depends-on "pdf-tools")
 (depends-on "polymode")
 (depends-on "poly-markdown")
 (depends-on "poly-R")
 (depends-on "popwin")
 (depends-on "prodigy")
 (depends-on "powerline")
 (depends-on "prescient")
 (depends-on "projectile")
 (depends-on "pyvenv")
 (depends-on "rainbow-delimiters")
 (depends-on "ranger")
 (depends-on "rtags")
 (depends-on "rg")
 (depends-on "s")
 (depends-on "slack")
 (depends-on "smartparens")
 (depends-on "smex")
 (depends-on "sublimity")
 (depends-on "swiper")
 (depends-on "tabbar" :git "https://github.com/dholm/tabbar.git")
 (depends-on "treemacs")
 (depends-on "treemacs-evil")
 (depends-on "treemacs-projectile")
 (depends-on "treemacs-icons-dired")
 (depends-on "treemacs-magit")
 (depends-on "undercover")
 (depends-on "use-package")
 (depends-on "vterm")
 (depends-on "web-mode")
 (depends-on "yasnippet")
 (depends-on "yasnippet-snippets")
 (depends-on "counsel-projectile")
 (depends-on "which-key")
 )
